--- 
date: 2015/01/06
published: true
tags: 
  - introduction
  - six-games-in-a-year
  - 2d-morpg
title: An epic journey of a man from beginner to pro in game programming
preview: > 
  Hi, I'm Mauno V채h채 and I have an interesting journey ahead. But first, let me briefly introduce myself.
  I'm a 28 years old, programmer by work/hobby, student, CS:GO player and a dude (obviously).
  I've been programming for a quite sometime, many years actually...
---
date: 2015/03/08
published: true
tags: 
  - website
  - mmo-server
  - games
title: Things I have build during the year 2015
preview: > 
  Hi, I'm Mauno V채h채 and I have an interesting journey ahead. But first, let me briefly introduce myself.
  I'm a 28 years old, programmer by work/hobby, student, CS:GO player and a dude (obviously).
  I've been programming for a quite sometime, many years actually...